# Generated by Django 3.0.6 on 2020-05-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.TextField(max_length=30)),
                ('line2', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LowerThird.Program')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LowerThird.Scene')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('program', 'order')},
            },
        ),
        migrations.AddField(
            model_name='program',
            name='scenes',
            field=models.ManyToManyField(through='LowerThird.ProgramScene', to='LowerThird.Scene'),
        ),
    ]
