# Generated by Django 3.0.6 on 2020-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='line1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='scene',
            name='line2',
            field=models.CharField(max_length=50),
        ),
    ]
