# Generated by Django 3.0.6 on 2020-05-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0003_auto_20200520_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='name',
        ),
    ]
