# Generated by Django 3.0.6 on 2020-05-21 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0005_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('Init', 'Initialising'), ('Blank', 'Blank'), ('Active', 'Active')], default='Init', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LowerThird.Program'),
        ),
        migrations.AlterField(
            model_name='session',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LowerThird.Scene'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(default='gtpbv', max_length=5),
        ),
    ]
