# Generated by Django 3.0.6 on 2020-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0006_auto_20200521_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(default='ifgv6', max_length=5, unique=True),
        ),
    ]
