# Generated by Django 3.0.6 on 2020-05-21 13:19

import LowerThird.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0007_auto_20200521_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(default=LowerThird.models.new_session, max_length=5, unique=True),
        ),
    ]
