# Generated by Django 2.2.12 on 2020-05-22 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0009_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='scenes',
        ),
        migrations.AlterField(
            model_name='programscene',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='LowerThird.Program'),
        ),
    ]
