# Generated by Django 2.2.13 on 2020-07-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0010_auto_20200522_1853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programscene',
            unique_together=set(),
        ),
    ]
