# Generated by Django 2.2.13 on 2020-08-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0011_auto_20200719_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='line1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scene',
            name='line2',
            field=models.CharField(max_length=80),
        ),
    ]
