# Generated by Django 3.1.3 on 2020-12-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0013_auto_20200815_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programscene',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='LowerThird.program'),
        ),
        migrations.AlterField(
            model_name='programscene',
            name='scene',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LowerThird.scene'),
        ),
    ]
