# Generated by Django 3.1.3 on 2020-12-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0014_auto_20201213_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programscene',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='LowerThird.program'),
        ),
    ]
