# Generated by Django 3.1.3 on 2020-12-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0015_auto_20201213_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='scene',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='LowerThird.program'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProgramScene',
        ),
    ]
