# Generated by Django 3.2.3 on 2021-05-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0017_program_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='persistent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='archived',
            field=models.BooleanField(default=False, help_text="Archived programs don't appear in the selection list for new sessions"),
        ),
    ]
