# Generated by Django 3.2.3 on 2021-09-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0018_auto_20210529_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LowerThird.program'),
        ),
        migrations.AlterField(
            model_name='session',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LowerThird.scene'),
        ),
    ]
