# Generated by Django 3.2.3 on 2021-05-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0018_auto_20210405_1405'),
        ('LowerThird', '0018_auto_20210529_1536'),
    ]

    operations = [
    ]
