# Generated by Django 3.2.3 on 2021-09-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LowerThird', '0019_auto_20210911_1731'),
        ('LowerThird', '0019_merge_0018_auto_20210405_1405_0018_auto_20210529_1536'),
    ]

    operations = [
    ]
