# Generated by Django 2.2.13 on 2020-06-29 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current', models.PositiveSmallIntegerField(default=0)),
                ('peak', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
