# Generated by Django 2.2.13 on 2020-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Count', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycount',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
