# Generated by Django 2.2.13 on 2020-07-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Count', '0003_auto_20200706_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ImageField(blank=True, editable=False, upload_to='')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Count.DayCount')),
            ],
        ),
    ]
