# Generated by Django 2.2.13 on 2020-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Count', '0004_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.ImageField(blank=True, editable=False, upload_to='graphs/'),
        ),
    ]
